force-app/main/default/objects/Product2/fields/Car_Brand__c.field-meta.xml
<CustomField>
    <fullName>Car_Brand__c</fullName>
    <label>Car Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Jeep</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Car_color__c.field-meta.xml
<CustomField>
    <fullName>Car_color__c</fullName>
    <label>Car color</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Car_model__c.field-meta.xml
<CustomField>
    <fullName>Car_model__c</fullName>
    <label>Car model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fiesta</fullName>
            </value>
            <value>
                <fullName>Focus</fullName>
            </value>
            <value>
                <fullName>Fusion</fullName>
            </value>
            <value>
                <fullName>Explorer</fullName>
            </value>
            <value>
                <fullName>Accord</fullName>
            </value>
            <value>
                <fullName>Civic</fullName>
            </value>
            <value>
                <fullName>CR-V</fullName>
            </value>
            <value>
                <fullName>Oddysey</fullName>
            </value>
            <value>
                <fullName>Versa</fullName>
            </value>
            <value>
                <fullName>Sentra</fullName>
            </value>
            <value>
                <fullName>Altima</fullName>
            </value>
            <value>
                <fullName>Murano</fullName>
            </value>
            <value>
                <fullName>Yaris</fullName>
            </value>
            <value>
                <fullName>Corolla</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>Prius</fullName>
            </value>
            <value>
                <fullName>Patriot</fullName>
            </value>
            <value>
                <fullName>Wangler</fullName>
            </value>
            <value>
                <fullName>Grand Cherokee</fullName>
            </value>
            <value>
                <fullName>Liberty</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
                <isActive>false</isActive>
                <label>SUV</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Vehicle_type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_type__c</fullName>
    <label>Vehicle type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>Coupe</fullName>
            </value>
            <value>
                <fullName>Minivan</fullName>
            </value>
            <value>
                <fullName>Convertible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BC_ProductController.cls
public with sharing class BC_ProductController {
    @AuraEnabled
    public static List<productWrapper> getActiveProduct() {
        List<PriceBookEntry> lstpbe = [SELECT Product2.Id, Product2.Name, Product2.Car_model__c, Product2.Public_image__c,
                                        Product2.Car_color__c, Product2.Car_brand__c, Product2.ProductCode, Product2.IsActive, UnitPrice, Product2.Vehicle_type__c
                                        FROM PriceBookEntry 
                                        WHERE Product2Id IN (SELECT Id 
                                                FROM Product2
                                                Product2 WHERE Public_image__c != '')];
        List<productWrapper> pdw = new List<productWrapper>();
        for(PriceBookEntry pbEntry : lstpbe) {
            productWrapper newProd = new productWrapper();
            newProd.Id = pbEntry.Product2.Id;
            newProd.productName = pbEntry.Product2.Car_model__c;
            newProd.productFamily = pbEntry.Product2.Car_brand__c;
            newProd.linkImage = pbEntry.Product2.Public_image__c;
            newProd.color = pbEntry.Product2.Car_color__c;
            newProd.price = String.valueOf(pbEntry.UnitPrice);
            newProd.isActive = pbEntry.Product2.IsActive;
            pdw.add(newProd);
        }
        return pdw;
    }
    @AuraEnabled(cacheable=true)
    public static List<productWrapper> searchedProds(){
        List<PriceBookEntry> lstpbe = [SELECT Product2.Id, Product2.Name, Product2.Car_model__c, Product2.Public_image__c,
                                       	Product2.Car_color__c, Product2.ProductCode, Product2.IsActive, UnitPrice, Product2.Vehicle_type__c
                               		   	FROM PriceBookEntry 
                               			WHERE Product2Id IN (SELECT Id 
                                                      FROM Product2
                                                      Product2 WHERE Public_image__c != '')];
        List<productWrapper> pdw = new List<productWrapper>();
        for(PriceBookEntry pbEntry : lstpbe) {
            productWrapper newProd = new productWrapper();
            newProd.Id = pbEntry.Product2.Id;
            newProd.productName = pbEntry.Product2.Car_model__c;
            newProd.productCode = pbEntry.Product2.ProductCode;
            newProd.productFamily = pbEntry.Product2.Family;
            newProd.linkImage = pbEntry.Product2.Public_image__c;
            newProd.color = pbEntry.Product2.Car_color__c;
            newProd.price = String.valueOf(pbEntry.UnitPrice);
            newProd.isActive = pbEntry.Product2.IsActive;
            pdw.add(newProd);
        }
        return pdw;
    }

    @AuraEnabled
    public static List<productWrapper> getProductsByQuery(String brand, String model, String vehicle) {
        Set<Id> productIds = new Set<Id>();
        List<Product2> records = new List<Product2>();
        String link = '';
	
        String query = 'SELECT Id from Product2 WHERE Public_image__c !=:link';
        if (!string.isEmpty(brand))        
        {
            query+=' and Car_Brand__c=:brand';
        } else {
            if (!string.isEmpty(model))        
            {
                query+=' and Car_model__c=:model';  
            }
            if (!String.isEmpty(vehicle))        
            {
                query+=' and Vehicle_type__c=:vehicle';
            }
        }
     	records = Database.query(query);
        System.debug('Records =======> '+records);
        for(Product2 prod : records) {
            productIds.add(prod.Id);
        }
        List<PriceBookEntry> lstpbe = [SELECT Product2.Id, Product2.Name, Product2.Car_Brand__c, Product2.Car_model__c, Product2.Public_image__c,
                                       	Product2.Car_color__c, Product2.ProductCode, Product2.IsActive, UnitPrice, Product2.Vehicle_type__c
                               		   	FROM PriceBookEntry 
                               			WHERE Product2Id IN :productIds];
        List<productWrapper> pdw = new List<productWrapper>();
        for(PriceBookEntry pbEntry : lstpbe) {
            productWrapper newProd = new productWrapper();
            newProd.Id = pbEntry.Product2.Id;
            newProd.productName = pbEntry.Product2.Car_model__c;
            newProd.productCode = pbEntry.Product2.ProductCode;
            newProd.productFamily = pbEntry.Product2.Car_model__c;
            newProd.linkImage = pbEntry.Product2.Public_image__c;
            newProd.color = pbEntry.Product2.Car_color__c;
            newProd.price = String.valueOf(pbEntry.UnitPrice);
            newProd.isActive = pbEntry.Product2.IsActive;
            pdw.add(newProd);
        }
        System.debug('productWrapper =========> '+pdw);
        return pdw;
    }

    public class productWrapper {
        @AuraEnabled public String Id;
        @AuraEnabled public String productName;
        @AuraEnabled public String productCode;
        @AuraEnabled public String vehicle;
        @AuraEnabled public String productFamily;
        @AuraEnabled public String linkImage;
        @AuraEnabled public String color;
        @AuraEnabled public String price;
        @AuraEnabled public Boolean isActive;
        @AuraEnabled public String description;
    }
}